name: dji_mapper
description: "Plan Survey & Photogrammetry Missions to use directly on your DJI Drone from the DJI Fly app"

publish_to: "none"

version: 1.5.0+7

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  dynamic_color: ^1.8.1
  flutter:
    sdk: flutter
  flutter_map: ^8.2.1
  flutter_map_line_editor: ^8.0.0
  flutter_spinbox: ^0.13.1
  latlong2: ^0.9.0
  provider: ^6.1.5
  xml: ^6.6.1
  dji_waypoint_engine:
    path: ./packages/dji_waypoint_engine
  litchi_waypoint_engine:
    path: ./packages/litchi_waypoint_engine
  flutter_map_dragmarker: ^8.0.3
  shared_preferences: ^2.5.3
  flutter_map_cancellable_tile_provider: ^3.1.1
  archive: ^3.6.1
  file_picker: ^10.3.2
  path: ^1.9.0
  universal_html: ^2.3.0
  url_launcher: ^6.3.1
  geolocator: ^14.0.2
  dio: ^5.9.0
  package_info_plus: ^8.3.1
  geoxml: ^2.6.2
  universal_io: ^2.2.2

dependency_overrides:
  geolocator_android: 4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/litchi_alert/
